{% set version = "0.2" %}

package:
    name: megaman
    version: {{ version }}

source:
    fn: megaman-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/m/megaman/megaman-{{ version }}.tar.gz
    md5: 4039b7e7845cf0345c87b75a9fc08fb1

build:
    number: 2
    skip: true    # [win]

requirements:
    build:
        - python
        - numpy x.x
        - cython
        - flann
        - gcc          # [unix]
    run:
        - python
        - numpy x.x
        - scipy >=0.16
        - scikit-learn >=0.17
        - pyamg
        - pyflann
        - libgcc       # [unix]

test:
    requires:
        - nose
    imports:
        - megaman
        - megaman.geometry
        - megaman.embedding
        - megaman.utils

about:
    home: http://mmp2.github.io/megaman
    license: BSD 2-clause
    license_file: LICENSE
    summary: "Manifold Learning for Millions of Points"

extra:
    recipe-maintainers:
        - jakevdp
