travis:
  secure:
    BINSTAR_TOKEN: SMSS21Ja9INavqfje+a5hxAslyvQwnq2Wo3y3jOqokBjoHurdrb7UyvTKgA+kOh4OszAF6xWAJIPpkEF/7WnFqz/cRGNaKrHxk8z7ZOHILxpfbFVpFl22TutS8RbRQ638LLRoWemHgJDKBivK5h/QOIdfkbMqiJKSEZT44eXI4BU0YYUL5ulphsB4e2r2YYhWZrUaOQEO+d06pufOJBYCHqj36Ciox9atEoxnYuP+p54EtE40cTDl9XdUHoJrHCfoOHRbltdVFmvkMcJx4AVCD0nygnTShPWgSESMpztgSRY6T6zRrVGP0Gmlnt7g8mHiiVMK+AeAz5Z0mqkqVNcTVF79hBe2pQU9oHzaMyX7vPwvn8jglOvUY0hbWhP3KgL8bmWB6X5Px86pYQ4BDvit58cUvADoHEzzkpUk7894mFmyztM0Y3Sg73HRsRvwTIcA/lm7QdSzUx09LSf+QeYqpfMVYABIUD1Y5S5EdGLs6h5HfKPLjaBxbdSCBPxehTbjm+PLzNcu2n/4mOcBhZ1IDMnUyUHSx6QsAzZZTNbajSDtZK118O1nP5S+Jpc7YGdCKLUgXFiFuzStHROo5rlEzIkUHnZflPoxeA13BhuNMbEzHjcbJkFr4SgPm+CXPMjK5o94sBUgb7iMs8KjCcfQgnF++urceoK9EaZgwQFtzQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
